name: "test"
backend: "python"
input [{name: "prompt", dims: [1], data_type: TYPE_STRING}]
output [{name: "generated_text", dims: [1], data_type: TYPE_STRING}]
instance_group [
  {
    kind: KIND_GPU
  }
]